name: validate

on:
  pull_request:
  push:

jobs:
  json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Validate JSON files
        run: |
          pip install jsonschema
          jsonschema -o pretty --instance data/aws.json schema.json
          jsonschema -o pretty --instance data/azure.json schema.json
          jsonschema -o pretty --instance data/cmp.json schema.json
          jsonschema -o pretty --instance data/credits.json schema.json
          jsonschema -o pretty --instance data/finance.json schema.json
          jsonschema -o pretty --instance data/gcp.json schema.json
          jsonschema -o pretty --instance data/gsuite.json schema.json
          jsonschema -o pretty --instance data/ms365.json schema.json
